services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    restart: unless-stopped
    volumes:
      - ./prometheus:/etc/prometheus
      - prom_data:/prometheus
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
    volumes:
      - ./grafana:/etc/grafana/provisioning
  powermeter-prometheus-exporter:
    image: powermeter-prometheus-exporter:latest
    container_name: powermeter-prometheus-exporter
    restart: unless-stopped
    ports:
      - 9100:9100
    environment:
      - POWERMETER_CONN="192.168.1.200:502"
volumes:
  prom_data:
