{
 "title": "Powermeter",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Momentanleistung",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "powermeter_power_active_w", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Netzspannung",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "powermeter_voltage_l1_v", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Strom",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "powermeter_current_l1_a", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Scheinleistung",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "voltamp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "powermeter_power_apparent_va", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Momentanleistung",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    { "expr": "powermeter_power_active_w", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Gesamtverbrauch",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "powermeter_energy_total_kwh", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Netzfrequenz",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "powermeter_frequency_hz", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Leistungsfaktor",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "powermeter_power_factor", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Blindleistung",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "voltampreact" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "powermeter_power_reactive_var", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Strom",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "powermeter_current_l1_a", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Netzspannung",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "powermeter_voltage_l1_v", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Blindleistung",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "powermeter_power_reactive_var", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Netzfrequenz",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    { "expr": "powermeter_frequency_hz", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Leistungsfaktor",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    { "expr": "powermeter_power_factor", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Scheinleistung",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    { "expr": "powermeter_power_apparent_va", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Gesamtverbrauch",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    { "expr": "powermeter_energy_total_kwh", "legendFormat": "__auto" }
   ]
  }
 ]
}